name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - agent/**
      # uncomment the next line if you want CI on direct pushes to main
      # - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality gates
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NODE_ENV: test
      # These are read by your integration tests
      TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
      TODOIST_TEST_PROJECT_ID: ${{ secrets.TODOIST_TEST_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Typecheck
        run: yarn tsc -p tsconfig.json --noEmit

      - name: Lint
        # Run eslint directly to avoid --fix in your "lint" script
        run: yarn eslint "{src,apps,libs,test}/**/*.ts" --max-warnings=0

      - name: Tests (unit + integration)
        run: yarn test:ci

      - name: Upload coverage on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage/**
            junit.xml
