name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - agent/**
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality gates
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      NODE_ENV: test
      # expose secrets to steps; will be empty on forks
      TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Typecheck
        run: yarn ci:typecheck

      - name: Lint
        run: yarn ci:lint

      - name: Unit tests
        run: yarn ci:test

      - name: Decide if we can run E2E/Integration
        id: gate
        shell: bash
        run: |
          RUN_E2E=false
          if [[ -n "${TODOIST_API_TOKEN}" && -n "${ANTHROPIC_API_KEY}" ]]; then
            if [[ "${{ github.event_name }}" == "push" ]]; then
              RUN_E2E=true
            elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.fork }}" == "false" ]]; then
              RUN_E2E=true
            fi
          fi
          echo "RUN_E2E=${RUN_E2E}" >> "$GITHUB_ENV"

      - name: Test E2E
        if: env.RUN_E2E == 'true'
        run: yarn ci:test:e2e

      - name: Test Integration
        if: env.RUN_E2E == 'true'
        run: yarn ci:test:integration

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics
          path: |
            coverage/**
            junit.xml
